apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-config
  namespace: dmrs
data:
  application.conf: |
    play.http.secret.key = "yb0Dt50495oPXYYYDY0avaLMvc0YbBTN6mYxj4vuSRPVsGdICt4MFkdZBiEXdC7l"
    analyzer {
      urls = [
        "/opt/Custom-Analyzers/analyzers"
      ]

      fork-join-executor {
        parallelism-min = 2
        parallelism-factor = 2.0
        parallelism-max = 4
      }
    }

    cortex {
      job-directory = "/opt/cortex/jobs"
      ports {
        http = 9001
      }
    }

    search {
      index = cortex
      uri = "http://thehive-elasticsearch.dmrs.svc.cluster.local:9200"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex
  namespace: dmrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex
  template:
    metadata:
      labels:
        app: cortex
    spec:
      containers:
        - name: cortex
          image: registry.digitalocean.com/dmrs-1/cortex-custom:latest
          ports:
            - containerPort: 9001
          command: ["/opt/cortex/bin/cortex"]
          args: ["-Dconfig.file=/etc/cortex/application.conf"]
          volumeMounts:
            - name: config
              mountPath: /etc/cortex/application.conf
              subPath: application.conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: cortex-config
      
---
apiVersion: v1
kind: Service
metadata:
  name: cortex
  namespace: dmrs
spec:
  type: NodePort
  selector:
    app: cortex
  ports:
    - port: 9001
      targetPort: 9001
      nodePort: 30002
