---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thehive-cassandra
  namespace: dmrs
spec:
  serviceName: thehive-cassandra
  replicas: 1
  selector:
    matchLabels:
      app: thehive-cassandra
  template:
    metadata:
      labels:
        app: thehive-cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:4.1
          ports:
            - containerPort: 9042
          resources:
            requests:
              memory: 2Gi
              cpu: 500m
            limits:
              memory: 3Gi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: thehive-cassandra
  namespace: dmrs
spec:
  type: ClusterIP
  selector:
    app: thehive-cassandra
  ports:
    - port: 9042
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thehive-elasticsearch
  namespace: dmrs
spec:
  serviceName: thehive-elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: thehive-elasticsearch
  template:
    metadata:
      labels:
        app: thehive-elasticsearch
    spec:
      initContainers:
        - name: init
          image: busybox
          command: ['sh', '-c', 'echo "Init done"']
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: thehive-elasticsearch
  namespace: dmrs
spec:
  type: ClusterIP
  selector:
    app: thehive-elasticsearch
  ports:
    - port: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thehive-minio
  namespace: dmrs
spec:
  serviceName: thehive-minio
  replicas: 1
  selector:
    matchLabels:
      app: thehive-minio
  template:
    metadata:
      labels:
        app: thehive-minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio
          args:
            - server
            - /data
          env:
            - name: MINIO_ACCESS_KEY
              value: "minio"
            - name: MINIO_SECRET_KEY
              value: "minio123"
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: thehive-minio
  namespace: dmrs
spec:
  type: ClusterIP
  selector:
    app: thehive-minio
  ports:
    - port: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thehive-api
  namespace: dmrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thehive-api
  template:
    metadata:
      labels:
        app: thehive-api
    spec:
      containers:
        - name: thehive
          image: strangebee/thehive:5.2.4
          ports:
            - containerPort: 9000
          env:
            - name: CASSANDRA_CONTACT_POINTS
              value: thehive-cassandra
            - name: CASSANDRA_KEYSPACE
              value: thehive
            - name: ELASTICSEARCH_URL
              value: http://thehive-elasticsearch:9200
            - name: MINIO_ENDPOINT
              value: http://thehive-minio:9000
            - name: MINIO_ACCESS_KEY
              value: minio
            - name: MINIO_SECRET_KEY
              value: minio123
            - name: JAVA_OPTS
              value: "-Dhttp.address=0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: thehive-api
  namespace: dmrs
spec:
  type: NodePort
  selector:
    app: thehive-api
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30001
