apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-w2thive-config
  namespace: wazuh
data:
  custom-w2thive.py: |
    #!/var/ossec/framework/python/bin/python3
    import json, sys, os, re, logging, uuid
    from thehive4py.api import TheHiveApi
    from thehive4py.models import Alert, AlertArtifact

    lvl_threshold = 0
    suricata_lvl_threshold = 3
    debug_enabled = False
    info_enabled = True

    pwd = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
    log_file = '{0}/logs/integrations.log'.format(pwd)
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.WARNING)
    if info_enabled: logger.setLevel(logging.INFO)
    if debug_enabled: logger.setLevel(logging.DEBUG)
    fh = logging.FileHandler(log_file)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    fh.setFormatter(formatter)
    logger.addHandler(fh)

    def main(args):
        alert_file_location = args[1]
        thive_api_key = args[2]
        thive = args[3]
        thive_api = TheHiveApi(thive, thive_api_key)
        w_alert = json.load(open(alert_file_location))
        alt = pr(w_alert,'',[])
        format_alt = md_format(alt)
        artifacts_dict = artifact_detect(format_alt)
        alert = generate_alert(format_alt, artifacts_dict, w_alert)
        if w_alert['rule']['groups']==['ids','suricata']:
            if 'data' in w_alert and 'alert' in w_alert['data']:
                if int(w_alert['data']['alert']['severity'])<=suricata_lvl_threshold:
                    send_alert(alert, thive_api)
        elif int(w_alert['rule']['level'])>=lvl_threshold:
            send_alert(alert, thive_api)

    def pr(data,prefix, alt):
        for key,value in data.items():
            if hasattr(value,'keys'):
                pr(value,prefix+'.'+str(key),alt=alt)
            else:
                alt.append((prefix+'.'+str(key)+'|||'+str(value)))
        return alt

    def md_format(alt,format_alt=''):
        md_title_dict = {}
        for now in alt:
            now = now[1:]
            dot = now.split('|||')[0].find('.')
            if dot==-1:
                md_title_dict[now.split('|||')[0]] =[now]
            else:
                if now[0:dot] in md_title_dict:
                    (md_title_dict[now[0:dot]]).append(now)
                else:
                    md_title_dict[now[0:dot]]=[now]
        for now in md_title_dict:
            format_alt+='### '+now.capitalize()+'\n'+'| key | val |\n| ------ | ------ |\n'
            for let in md_title_dict[now]:
                key,val = let.split('|||')[0],let.split('|||')[1]
                format_alt+='| **' + key + '** | ' + val + ' |\n'
        return format_alt

    def artifact_detect(format_alt):
        artifacts_dict = {}
        artifacts_dict['ip'] = re.findall(r'\d+\.\d+\.\d+\.\d+',format_alt)
        artifacts_dict['url'] =  re.findall(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+',format_alt)
        artifacts_dict['domain'] = [url.split('//')[1].split('/')[0] for url in artifacts_dict['url']]
        return artifacts_dict

    def generate_alert(format_alt, artifacts_dict,w_alert):
        sourceRef = str(uuid.uuid4())[0:6]
        artifacts = []
        if 'agent' in w_alert:
            if 'ip' not in w_alert['agent']:
                w_alert['agent']['ip']='no agent ip'
        else:
            w_alert['agent'] = {'id':'no agent id', 'name':'no agent name'}
        for key,value in artifacts_dict.items():
            for val in value:
                artifacts.append(AlertArtifact(dataType=key, data=val))
        alert = Alert(title=w_alert['rule']['description'],
                  tlp=2,
                  tags=['wazuh',
                  'rule='+w_alert['rule']['id'],
                  'agent_name='+w_alert['agent']['name'],
                  'agent_id='+w_alert['agent']['id'],
                  'agent_ip='+w_alert['agent']['ip']],
                  description=format_alt,
                  type='wazuh_alert',
                  source='wazuh',
                  sourceRef=sourceRef,
                  artifacts=artifacts)
        return alert

    def send_alert(alert, thive_api):
        response = thive_api.create_alert(alert)
        if response.status_code == 201:
            logger.info('Create TheHive alert: '+ str(response.json()['id']))
        else:
            logger.error('Error create TheHive alert: {}/{}'.format(response.status_code, response.text))

    if __name__ == "__main__":
        try:
           logger.debug('debug mode')
           main(sys.argv)
        except Exception:
           logger.exception('Exception occurred')
  custom-w2thive: |
      #!/bin/sh
      # Copyright (C) 2015-2020, Wazuh Inc.
      # Created by Wazuh, Inc. <info@wazuh.com>.
      # This program is free software; you can redistribute it and/or modify it under the terms of GPL
  
      WPYTHON_BIN="framework/python/bin/python3"
      SCRIPT_PATH_NAME="$0"
      DIR_NAME="$(cd $(dirname "${SCRIPT_PATH_NAME}"); pwd -P)"
      SCRIPT_NAME="$(basename "${SCRIPT_PATH_NAME}")"
  
      case "${DIR_NAME}" in
          */active-response/bin | */wodles*)
              [ -z "${WAZUH_PATH}" ] && WAZUH_PATH="$(cd "${DIR_NAME}/../.."; pwd)"
              PYTHON_SCRIPT="${DIR_NAME}/${SCRIPT_NAME}.py"
              ;;
          */bin)
              [ -z "${WAZUH_PATH}" ] && WAZUH_PATH="$(cd "${DIR_NAME}/.."; pwd)"
              PYTHON_SCRIPT="${WAZUH_PATH}/framework/scripts/${SCRIPT_NAME}.py"
              ;;
          */integrations)
              [ -z "${WAZUH_PATH}" ] && WAZUH_PATH="$(cd "${DIR_NAME}/.."; pwd)"
              PYTHON_SCRIPT="${DIR_NAME}/${SCRIPT_NAME}.py"
              ;;
      esac
  
      "${WAZUH_PATH}/${WPYTHON_BIN}" "${PYTHON_SCRIPT}" "$@"